"""Rename borrower_email to borrower_email and add borrower_phone

Revision ID: 1668eb83cebd
Revises: d806cab96be9
Create Date: 2025-11-19 00:22:55.332324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1668eb83cebd'
down_revision = 'd806cab96be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_phone', sa.String(length=100), nullable=False))
        batch_op.alter_column(
            'borrower_contact' ,
            new_column_name='borrower_email',
            existing_type=sa.String(length=100),
            existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column(
            'borrower_email',
            new_column_name='borrower_contact',
            existing_type=sa.String(length=100),
            existing_nullable=False
        )
        batch_op.drop_column('borrower_phone')
        

    # ### end Alembic commands ###
