"""add user_email field to booking table

Revision ID: 34149e0aaa5b
Revises: 2e88591db664
Create Date: 2025-11-22 17:57:12.727391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34149e0aaa5b'
down_revision = '2e88591db664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_email', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('use_email')

    # ### end Alembic commands ###
