"""add phone and course to user; add programme table

Revision ID: 47fd70a86e97
Revises: 6af8a26a7479
Create Date: 2026-03-04 10:23:40.749357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fd70a86e97'
down_revision = '6af8a26a7479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create programme table only if it doesn't already exist
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'programme' not in inspector.get_table_names():
        op.create_table(
            'programme',
            sa.Column('id',   sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=200), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name'),
        )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone',  sa.String(length=30),  nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('course')
        batch_op.drop_column('phone')

    op.drop_table('programme')
    # ### end Alembic commands ###
