"""add denial_reason to booking

Revision ID: 62a223514ffe
Revises: 6d9e9e16b3b9
Create Date: 2026-10-08 22:23:27.866349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a223514ffe'
down_revision = '6d9e9e16b3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('denial_reason', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('denial_reason')

    # ### end Alembic commands ###
