"""add booking_items and location tables

Revision ID: 6af8a26a7479
Revises: bc67bb4d8cbb
Create Date: 2026-03-03 21:56:10.412938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af8a26a7479'
down_revision = 'bc67bb4d8cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=300), nullable=True))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bookable', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('is_bookable')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
