"""add max_booking_days to item, created_at and status_changed_at to booking

Revision ID: b11084c2f89c
Revises: 47fd70a86e97
Create Date: 2026-10-03 10:57:17.138655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11084c2f89c'
down_revision = '47fd70a86e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status_changed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_booking_days', sa.Integer(), server_default='8', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('max_booking_days')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('status_changed_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
