"""corrected typo of user_email on booking table

Revision ID: bc67bb4d8cbb
Revises: 34149e0aaa5b
Create Date: 2025-11-22 19:54:21.885519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc67bb4d8cbb'
down_revision = '34149e0aaa5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=100), nullable=False))
        batch_op.drop_column('use_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False))
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
