"""added bulk edit, pages for item details and styles

Revision ID: d806cab96be9
Revises: 
Create Date: 2024-02-19 07:57:51.719802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd806cab96be9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('borrower_name', sa.String(length=100), nullable=False),
    sa.Column('borrower_email', sa.String(length=100), nullable=False),
    sa.Column('borrow_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('borrower_name')
        batch_op.drop_column('borrow_date')
        batch_op.drop_column('borrower_email')
        batch_op.drop_column('status')
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('borrower_email', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('borrow_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('borrower_name', mysql.VARCHAR(length=100), nullable=True))

    op.drop_table('booking')
    # ### end Alembic commands ###
