"""add receives_admin_emails to user

Revision ID: e9a4b86a213f
Revises: b11084c2f89c
Create Date: 2026-10-03 12:23:46.344999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a4b86a213f'
down_revision = 'b11084c2f89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receives_admin_emails', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('receives_admin_emails')

    # ### end Alembic commands ###
